spaceplanner/urls.py
from django.urls import path, include
from rest_framework.urlpatterns import format_suffix_patterns

from . import views

app_name = 'spaceplanner'
urlpatterns = [
    path('', views.home, name='home'),
    path('out_of_range', views.out_of_range, name = 'out_of_range'),
    path('user_panel/', views.user_panel, name='user_panel'),
    path('user_panel/<date>', views.user_panel, name='user_panel'),
    path('schedule_week/<int:pk>/', views.schedule_week, name='schedule_week'),
    path('edit_preferences/', views.edit_preferences, name='edit_preferences'),
    path('workstation_schedule/<date>', views.workstation_schedule, name='workstation_schedule'),
    path('workstation_preferences', views.workstation_preferences, name='workstation_preferences'),
    path('edit_information', views.edit_information, name='edit_information'),
    path('i18n/', include('django.conf.urls.i18n')),
    path('accounts/', include('django.contrib.auth.urls')),
]

#RestApi patterns
urlpatterns += [
    path('workstations/', views.WorkstationList.as_view()),
    path('workstations/<int:pk>/', views.WorkstationDetail.as_view()),
    path('workstation_preferences/', views.WorkstationPreferencesList.as_view()),
    path('workstation_preferences/<int:pk>/', views.WorkstationPreferencesDetail.as_view(), name='workstation-preference-detail'),
    path('employee_preferences/', views.EmployeePreferencesList.as_view()),
    path('employee_preferences/<int:pk>/', views.EmployeePreferencesDetail.as_view(), name='employee-preference-detail'),
    path('workweeks/', views.WorkweekList.as_view()),
    path('workweeks/<int:pk>/', views.WorkweekDetail.as_view()),
    path('userweeks/', views.UserweekList.as_view()),
    path('userweeks/<int:pk>/', views.UserweekDetail.as_view()),
    path('users/', views.UserList.as_view()),
    path('users/<int:pk>/', views.UserDetail.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)

spaceplanner/templates/spaceplanner/edit_information.html
{% extends "base_generic.html" %}

{% load i18n %}

{% block content %}
<body>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="{% trans 'Change' %}">
    </form>
</body>
</html>
{% endblock %}

spaceplanner/templates/spaceplanner/edit_preferences.html
{% extends "base_generic.html" %}

{% load i18n %}

{% block content %}
<body>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <p>{% trans 'Edit preferences page' %}</p>
    <form method="POST" class="preferences-form">{% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                {% for error in field.errors %}
                    <div class="alert alert-danger">
                    {{ error|escape }}
                    </div>
                {% endfor %}
                {{ field.label }}
                {{ field }}       
            </div>
        {% endfor %}
        <button type="submit" class="save btn btn-default">{% trans 'Save' %}</button>
    </form>
</body>
</html>
{% endblock %}

spaceplanner/templates/spaceplanner/home.html
{% extends "base_generic.html" %}

{% load i18n %}

{% block content %}
<body>
    <p class='headline'>{% trans 'Welcome to OS Planner' %}</p>
</body>
</html>
{% endblock %}

spaceplanner/templates/spaceplanner/out_of_range.html
{% extends "base_generic.html" %}

{% load staticfiles %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/styles.css' %}">
<body class='oor-body'>
    <p class='headline'>{% trans 'Chosen date is out of range' %}</p>
    <a class="btn btn-primary" id='or-button' href="{% url 'spaceplanner:user_panel' %}">{% trans 'Return to main page' %}</a>
</body>
</html>
{% endblock %}

spaceplanner/templates/spaceplanner/schedule_button.html
{% load i18n %} 
<a class="btn btn-primary" href="{% url 'spaceplanner:schedule_week' record.pk %}">{% trans "Schedule Week" %}</a>

spaceplanner/templates/spaceplanner/schedule_week.html
{% extends "base_generic.html" %}

{% load i18n %}

{% load staticfiles %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/styles.css' %}">
<body>
    <p>{% trans 'Date' %}: {{ userweek.year }}|{{userweek.week}}, {{date_range}} </p>
    <p>{% trans 'Choose workstation manually:' %}</p>
    <form method="POST" class="schedule-form">
        {% csrf_token %}
        {% for field in editform %}
            <p>{{ field.label }} {{ field }}</p>
        {% endfor %}
        <button type="submit" class="button" name="editweek">{% trans 'Save' %}</button>
    </form>
    <p class="empty-space"></p>
    
    <p>{% trans 'Authomatic scheduler' %}</p>
    <form method='POST'>
        {% csrf_token %}
        {{ generateform.as_p }}
        <button type="submit" class="button" name="generateweek">{% trans 'Save' %}</button>
    </form>
    <p class="empty-space"></p>
    <div class="sw-control-buttons">
        <div id="sw-clear-schedule">
            <form method='POST'>
                {% csrf_token %}
                <input type="submit" class="button" value="{% trans 'Clear Schedule' %}" name="mybtn">
            </form>
        </div>
        <a href="{% url 'spaceplanner:user_panel'%}" id="sw-cancel"><button>{% trans 'Cancel' %}</button></a>
    </div>
</body>
</html>
{% endblock %}

spaceplanner/templates/spaceplanner/user_panel.html
{% extends "base_generic.html" %}
{% load render_table from django_tables2 %}
{% load staticfiles %}

{% load i18n %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/styles.css' %}">
<body>
<div class='user-body'>
    {% if messages %}
        <ul class="messages" name="schedule_message">
        {% for message in messages %}
            <li class="{{ message.tags }}">{{ message }}</li>
        {% endfor %}
        </ul>
    </div>
    {% endif %}
    <a class='up-month-name'>{{date_name}}</a>
    <div class=up-date-buttons>
        <a class="btn btn-primary" href="{% url 'spaceplanner:user_panel' date=previous_date %}" id='change_date' >{% trans 'Previous' %}</a>
        <a class="btn btn-primary" href="{% url 'spaceplanner:user_panel' date=next_date %}" id='change_date'>{% trans 'Next' %}</a>
    </div>
    {% render_table table %}
    {% render_table preferences %}
    <div class=up-preference-buttons>
        <a class="btn btn-primary" href="{% url 'spaceplanner:edit_preferences' %}" id='edit_preferences_btn'>{% trans 'Edit preferences' %}</a>
        <a class="btn btn-primary" href="{% url 'spaceplanner:workstation_schedule' date=date %}", id='edit_preferences_btn'>{% trans 'Workstations schedule' %}</a>
        <a class="btn btn-primary" href="{% url 'spaceplanner:workstation_preferences'%}", id='edit_preferences_btn'>{% trans 'Workstations properties' %}</a>
    </div>
</div>
</body>
</html>
{% endblock %}

spaceplanner/templates/spaceplanner/view_button.html
{% load i18n %} 
<a class="btn btn-primary" href="{% url 'spaceplanner:schedule_week' record.pk %}">{% trans "View week" %}</a>

spaceplanner/templates/spaceplanner/workstation_preferences.html
{% extends "base_generic.html" %}
{% load render_table from django_tables2 %}
{% load staticfiles %}
{% load i18n %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/styles.css' %}">
<body>
<div class='workstation-schedule-body'>
    <p>{% trans 'Workstations preferences' %}</p>
    {% render_table table %}
</div>
</body>
</html>
{% endblock %}

spaceplanner/templates/spaceplanner/workstation_schedule.html
{% extends "base_generic.html" %}
{% load render_table from django_tables2 %}
{% load staticfiles %}

{% load i18n %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/styles.css' %}">
<body>
{% if messages %}
    <ul class="messages">
    {% for message in messages %}
        <li class="{{ message.tags }}">{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
<div class='workstation-schedule-body'>
    <p>{% trans 'Workstations schedule' %}</p>
    <div class=up-date-buttons>
        <a class="btn btn-primary" href="{% url 'spaceplanner:workstation_schedule' date=previous_date %}" id='change_date' >{% trans 'Previous' %}</a>
        <a class="btn btn-primary" href="{% url 'spaceplanner:workstation_schedule' date=next_date %}" id='change_date'>{% trans 'Next' %}</a>
    </div>
    <a class='up-month-name'>{{date_range}}</a>
    {% render_table table %}
</div>
</body>
</html>
{% endblock %}