spaceplanner/urls.py
from django.urls import path, include
from rest_framework.urlpatterns import format_suffix_patterns

from . import views

app_name = 'spaceplanner'
urlpatterns = [
    path('', views.home, name='home'),
    path('out_of_range', views.out_of_range, name = 'out_of_range'),
    path('user_panel/', views.user_panel, name='user_panel'),
    path('user_panel/<date>', views.user_panel, name='user_panel'),
    path('schedule_week/<int:pk>/', views.schedule_week, name='schedule_week'),
    path('edit_preferences/', views.edit_preferences, name='edit_preferences'),
    path('workstation_schedule/<date>', views.workstation_schedule, name='workstation_schedule'),
    path('workstation_preferences', views.workstation_preferences, name='workstation_preferences'),
    path('edit_information', views.edit_information, name='edit_information'),
    path('i18n/', include('django.conf.urls.i18n')),
    path('accounts/', include('django.contrib.auth.urls')),
]

#RestApi patterns
urlpatterns += [
    path('workstations/', views.WorkstationList.as_view()),
    path('workstations/<int:pk>/', views.WorkstationDetail.as_view()),
    path('workstation_preferences/', views.WorkstationPreferencesList.as_view()),
    path('workstation_preferences/<int:pk>/', views.WorkstationPreferencesDetail.as_view(), name='workstation-preference-detail'),
    path('employee_preferences/', views.EmployeePreferencesList.as_view()),
    path('employee_preferences/<int:pk>/', views.EmployeePreferencesDetail.as_view(), name='employee-preference-detail'),
    path('workweeks/', views.WorkweekList.as_view()),
    path('workweeks/<int:pk>/', views.WorkweekDetail.as_view()),
    path('userweeks/', views.UserweekList.as_view()),
    path('userweeks/<int:pk>/', views.UserweekDetail.as_view()),
    path('users/', views.UserList.as_view()),
    path('users/<int:pk>/', views.UserDetail.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)

spaceplanner/templates/base_generic.html
{% load i18n %}

<!DOCTYPE html>
<html lang="en" background-color: #b4b6a5>
<head>
  {% block title %}<title>OS Planner</title>
  {% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body class='main-body'>
    <div class="page-header">
        <h1><a href="/">OS Planner</a></h1>
        <!--
        <form action="{% url 'spaceplanner:set_language' %}" method="post" class=language-form>
            {% csrf_token %}
            <input name="next" type="hidden" value="{{ redirect_to }}" />
              {% get_current_language as LANGUAGE_CODE %}
              {% get_available_languages as LANGUAGES %}
              {% get_language_info_list for LANGUAGES as languages %}
              {% for language in languages %}
                <button type="submit" name="language" value="{{ language.code }}"
                  class="btn-kinito">
                  {{ language.code }}
                </button>
              {% endfor %}
          </form>
          -->
    </div>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
        <ul class="sidebar-nav">
          <li><a href="{% url 'spaceplanner:home' %}">{% trans 'Home' %}</a></li>
          {% if user.is_authenticated %}
            <li><a href="{% url 'spaceplanner:user_panel' %}">{% trans 'Scheduler' %}</a></li>
            <li><a href="{% url 'spaceplanner:edit_information'%}">{% trans 'Edit information' %}</a></li>
            <li><a href="{% url 'spaceplanner:password_change' %}">{% trans 'Change password' %}</a></li>
            <li><a href="{% url 'spaceplanner:logout'%}">{% trans 'Logout' %}</a></li>
          {% else %}
            <li><a href="{% url 'spaceplanner:login'%}">{% trans 'Login' %}</a></li>   
          {% endif %} 
        </ul>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">
        {% if user.is_authenticated %}
          <p class='headline'>{% trans 'Logged in as'%} {{ user.get_full_name }}</p>
        {% endif %}
          {% block content %}{% endblock %}
      </div>
    </div>
  </div>
  <p class='empty-space'></p>
</body>
</html>